version: "3.9"
services:
  docker-generate-sigma:
    image: zsusswein/indoor_outdoor:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    container_name: indoor_outdoor_main
# Set up a bind mount to the working dir so any edits from within the container 
# get saved to the files.
    volumes:
      - type: bind
        source: ./
        target: "/home/rstudio"
    environment:
      - PASSWORD=rstudio
