version: "3.9"
services:
  docker-generate-sigma:
    image: indoor_outdoor
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - type: bind
        source: "$PWD"
        target: "/home/rstudio/"
    environment:
      - PASSWORD=rstudio
